stages:
  - test
  - build

## cache composer packages between all jobs and all branches
cache:
  key: one-key-to-rull-them-all
  paths:
    - composer-cache/

test:
  image: cylab/php:7.4
  stage: test
  before_script:
    - COMPOSER_CACHE_DIR=composer-cache composer install
  script:
    - vendor/bin/phpunit --coverage-text --colors=never
    - vendor/bin/phpcs
    - vendor/bin/phpstan analyze

include:
  - component: $CI_SERVER_FQDN/components/docker/build-and-push@1.0.0
    inputs:
      stage: build
      docker_image: cylab/hello:latest
      docker_username: $DOCKER_USER
      docker_password: $DOCKER_PASSWORD
      
  - component: $CI_SERVER_FQDN/components/docker/build-and-push-local@1.3.0
    inputs:
      stage: build
      job_name: docker-build-and-push-local