stages:
  - test
  - build

## cache composer packages between all jobs and all branches
cache:
  key: one-key-to-rull-them-all
  paths:
    - composer-cache/

test:
  image: cylab/php:7.4
  stage: test
  before_script:
    - COMPOSER_CACHE_DIR=composer-cache composer install
  script:
    - vendor/bin/phpunit --coverage-text --colors=never
    - vendor/bin/phpcs
    - vendor/bin/phpstan analyze

build:1.0:
  stage: build
  # this job requires docker-in-docker
  tags:
    - dind
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  before_script:
    - docker info
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - git checkout 1.0
    - docker build --tag cylab/hello:1.0 .
    - docker push $cylab/hello:1.0

build:2.0:
  stage: build
  # this job requires docker-in-docker
  tags:
    - dind
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  before_script:
    - docker info
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - git checkout 2.0
    - docker build --tag cylab/hello:2.0 .
    - docker push $cylab/hello:2.0

build:latest:
  stage: build
  # this job requires docker-in-docker
  tags:
    - dind
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  before_script:
    - docker info
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - docker build --tag cylab/hello:latest .
    - docker push $cylab/hello:latest
